### PR TITLE
Merge config.properties and application.properties 

### LINKED ISSUE #75: Merge config.properties and application.properties
`config.properties` should be handled in a standard way for spring applications. Consider merging `config.properties` and `application.properties` to application.yml or applications.properties. Propose solution first.

### PR DESCRIPTION
**Pull request by palagdan**
Resolves #75

### CODE REVIEW

**Comment by palagdan** [comment]
@blcham

I have merged config.properties and application.properties into application.yml because I believe YAML is more readable than properties files. If you have a different opinion, I'd be happy to discuss it.

In the tests, I refactored configuration.properties to application.properties because it is not possible to convert it to YAML. The TestFormGenPersistenceFactory and TestPersistenceFactory classes use the annotation @PropertySource("classpath:application.properties"), which does not work with YAML files ([source](https://github.com/spring-projects/spring-framework/issues/21105)).

The solution might be to create a base test class with the @SpringBootTest annotation to easily load YAML configuration files. I tried this, but I encountered many errors related to the inability to create some beans, etc.

**Comment by blcham** [comment]
Have a look here:
https://github.com/kbss-cvut/termit/blob/master/src/test/resources/application.yml

**Comment by palagdan** [comment]
@blcham 

Since there are issues with the YAML files during testing, I suggest using application.properties in the src/ directory as well. There is no significant difference between .yml and .properties, except for syntax and parsers. Spring generally prefers .properties, especially when working with certain annotations like @PropertySource and @TestPropertySource.

**Comment by blcham** [comment]
@palagdan I did some investigation, and I came to the conclusion that .yml is a better choice mainly due to readability as we have quite many properties now. On the other hand, it is already implemented here as application.properties, so let's merge it and we will consider it someday later :), after we get rid of `@PropertySource` in favor of `@ConfigurationProperties`+`@EnableConfigurationProperties`.

Summary of my investigation:

**Pros:**
- more readable for bigger configuration like in RM
- supports not only key-value pair, but also map, list & scalar type values
**Cons:**
- YAML files can’t be loaded via the @PropertySource annotation. So in the case that you need to load values that way, you need to use a properties file.
- .properties files are simpler but really spread only in Java community, so i do not consider it that big advantage compared to .yml that is wide-spread in other comunities (e.g. python)

**Pull request merged**
